<?php

require 'authorisation.php';
require 'xcdb.php';

// Generate sanitised IGC files
function gen_track($link, $traPk, $date, $pilot, $altmax)
{
    $igcout = [];

    $igcout[] = "AXXXZZZairScore";
    $igcout[] = "HFDTE$date";
    $igcout[] = "HFPLTPILOT: $pilot";
    $igcout[] = "HFDTM100DATUM: WGS-1984";

    $sql = "SELECT TL.* from tblTrackLog TL where TL.traPk=$traPk order by TL.trlTime";
    $result = mysql_query($sql,$link) or json_die("Unable to find tracklog: " . mysql_error() . "\n");

    // B0442223707362S14524802EA0000000650
    $cross = 0;
    while($row = mysql_fetch_array($result, MYSQL_ASSOC))
    {
        $time = 0 + $row['trlTime'];
        $h = floor($time / 3600);
        if ($cross == 0 && $h > 24)
        {
            $cross = 1;
            // FIX: output a DTE again?
        }
        $m = floor(($time - $h * 3600)/60);
        $s = $time % 60;
        $ftime = sprintf("%02d%02d%02d",($h%24),$m,$s);

        $lat = floatval($row['trlLatDecimal']);
        if ($lat < 0)
        {
            $h = floor(abs($lat));
            $alat = round((abs($lat)-$h)*60000,0);
            $slat = sprintf("%02d%05dS",$h, $alat);
        }
        else
        {
            $h = floor($lat);
            $alat = round(($lat-$h)*60000,0);
            $slat = sprintf("%02d%05dN",$h, $alat);
        }
        $lon = floatval($row['trlLongDecimal']);
        if ($lon < 0)
        {
            $h = floor(abs($lon));
            $alon = round((abs($lon)-$h)*60000,0);
            $slon = sprintf("%03d%05dW",$h, $alon);
        }
        else
        {
            $h = floor($lon);
            $alon = round(($lon-$h)*60000,0);
            $slon = sprintf("%03d%05dE",$h, $alon);
        }

        // @todo: airspace check should flag tracks and return '0' alt if track is infringing?
        $altv = 0 + $row['trlAltitude'];

        // Don't show advertise really bad track to the public
        if ($altmax > 0 && $altv > $altmax)
        {
            $altv = $altmax - ($altv - $altmax);
        }

        $alt = sprintf("%05d", $altv);
        # convert lat/lon to NESW appropriately
        # get some decent date ..
        $igcout[] = "B${ftime}${slat}${slon}A00000${alt}";
    }
    # Footer
    #LXXXGenerated by GPSBabel Version 1.3.0
    #GGPSBabelSecurityRecordGuaranteedToFailVALIChecks
    $igcout[] = "LXXXGenerated by airScore 0.2";
    $igcout[] = "GFailed security check";

    $result = implode("\r\n", $igcout);

    return $result;
}

$traPk=reqival('traPk');
if (!$traPk)
{
    $traPk=reqival('trackid');
}
$tasPk=reqival('tasPk');
$count=reqival('count');
$comPk=reqival('comPk');

$link = db_connect();
$tracks = [];
$cominfo = [];
$altmax = 2590;
$usePk = check_auth('system');
if (is_admin('admin',$usePk,$comPk))
{
    $altmax = 0;
}

if ($tasPk > 0)
{
    $limit = '';
    if ($count > 0) 
    {
        $limit = " limit $count";
    }
    $cominfo = get_comtask($link, $tasPk);
    $comPk = $cominfo['comPk'];
    $date = $cominfo['tasDate'];
    //$sql = "select traPk from tblComTaskTrack where $tasPk $limit";
    $sql = "select date_format(T.traStart,'%d%m%y') as Start, TR.*, P.* from tblTaskResult TR, tblTrack T, tblPilot P where TR.tasPk=$tasPk and T.traPk=TR.traPk and P.pilPk=T.pilPk order by TR.tarScore desc $limit";
    $result = mysql_query($sql, $link) or json_die("can't get associated tracks");
    while ($row = mysql_fetch_array($result, MYSQL_ASSOC))
    {
        $tracks[] = $row;
    }
}
else if ($traPk > 0)
{
    $sql = "select comPk from tblComTaskTrack where traPk=$traPk";
    $result = mysql_query($sql, $link) or json_die("can't get associated comp");
    $comPk = mysql_result($result,0,0);

    $sql = "SELECT date_format(T.traStart,'%d%m%y') as Start, P.pilFirstName, P.pilLastName, T.traDate from tblTrack T, tblPilot P where T.traPk=$traPk and T.pilPk=P.pilPk";
    $result = mysql_query($sql, $link) or json_die("can't get track information");
    $row = mysql_fetch_array($result, MYSQL_ASSOC);
    $date = $row['Start'];
    $ndate = $row['traDate'];
    $pilot = $row['pilFirstName'] . ' ' . $row['pilLastName'];

    $trackstr = gen_track($link, $traPk, $date, $pilot, $altmax);
    header("Content-type: text/igc");
    header("Cache-Control: no-store, no-cache");
    header("Content-Disposition: attachment; filename=\"$ndate-$pilot.igc\"");
    print $trackstr;
    exit(0);
}
else if ($comPk > 0)
{
    $cominfo = get_comformula($link, $comPk);
    $sql = "select  T.traPk, date_format(T.traStart,'%H%d%m%y') as Start, P.pilFirstName, P.pilLastName, T.traDate, P.pilHGFA from tblComTaskTrack C, tblTrack T, tblPilot P where C.tasPk is null and C.comPk=$comPk and C.traPk=T.traPk and P.pilPk=T.pilPk";
    $result = mysql_query($sql, $link) or json_die("can't get associated tracks");
    while ($row = mysql_fetch_array($result, MYSQL_ASSOC))
    {
        $tracks[] = $row;
    }
    $tasPk="C$comPk";
}

$ziplist = [];
foreach ($tracks as $row)
{
    $pilot = $row['pilFirstName'] . ' ' . $row['pilLastName']; 
    $filename = preg_replace('/[\s+\/]/', '_', addslashes(strtolower( $row['pilLastName'] . '_' . $row['pilHGFA'] . '_' . $row['Start'] . '.igc')));
    mkdir("/tmp/$tasPk");
    $fname = "/tmp/$tasPk/" . $filename;
    if (!file_exists($fname))
    {
        $trackstr = gen_track($link, $row['traPk'], $row['Start'], $pilot, $altmax);
        file_put_contents($fname, $trackstr);
    }
    $ziplist[] = $filename;
}

# zip them up ..
$allfiles = implode(' ', $ziplist);
$bname = strtolower(preg_replace('/[\s+\/]/', '_', $cominfo['comName'] . '_' . $cominfo['tasName'] . ".zip"));
$filename = '/tmp/' . $bname;
#echo ("zip \"$filename\" $allfiles 2>&1 > /dev/null");
chdir("/tmp/$tasPk");
$line = system("zip \"$filename\" $allfiles 2>&1 > /dev/null", $retval);

if ($retval == 0)
{
    header("Content-Type: application/zip");
    header("Content-Disposition: attachment; filename=\"$bname\"");
    header("Content-Length: " . filesize($filename));
    readfile($filename);
}
else
{
    header("Content-type: text/plain");
    header("Cache-Control: no-store, no-cache");
    
    print "retval=$retval\n";
    print $line;
}


foreach ($ziplist as $filen)
{
    //unlink($filen);
}
//unlink($filename);
?>

